### ISSUE TITLE
[BUG] Stability issues with longer running ace-box instances

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#124]
**Describe the bug**
I noticed that after a while, the services (dashboard, jenkins, keptn, ...) of longer-running ace-box instances are no longer available. A restart/kill all pods seems to be resolving these issues. 

All the pods seem healthy, but cannot be reached. The VM is reachable via ssh.

Investigation needs to be done as to why this is happening and also how it can be resolved

Let's use this issue to file our findings and discuss a way forward.

**Comment by tobigremmer-dt** [comment]
New occurrence on December 13:
- Time since last occurrence (December 7): 6 days
- State of ACE-Box:
  - All pods running, except dynakube-activegate and shipyard-controller
  - Microk8s snap running (Next time: Check snap logs if available)
- Resolution steps:
  - Restarting ingress -> Not successful
  - Restarting shipyard-controller / dynakube-activegate -> Pods didn't become healthy, not successful
  - Restarting all pods -> Not successful
  - Restarting Microk8s snap -> Successful

Could this be a resource issue, e.g. something using all available mem/cpu?
