### ISSUE TITLE
[BUG] SRG demo incorrect objective

### ISSUE THREAD

**Issue by tobigremmer-dt** [Dynatrace/ace-box#521]
**Describe the bug**
The "Response Time of API Method" isn't working in `demo_release_validation_srg_gitlab`. See demo-sprint ( https://swv55769.sprint.apps.dynatracelabs.com/ui/apps/dynatrace.site.reliability.guardian/analysis/vu9U3hXa3q0AAAABADFhcHA6ZHluYXRyYWNlLnNpdGUucmVsaWFiaWxpdHkuZ3VhcmRpYW46Z3VhcmRpYW5zAAZ0ZW5hbnQABnRlbmFudAAkODE2YmY4NDgtMGFjYi0zODczLWE0M2MtOTY5OGE4NDg4Yzg3vu9U3hXa3q0?validationId=722d643c-79a6-4a7d-9b94-2b56f9be548f ) for details.

**Comment by eemrdog** [comment]
The issue is with the environment logs bucket configuration to be enabled to fetch the logs from Grail. When you run the DQL command on a notebook (i.e., fetch logs), it returns no value. However, we must add some prerequisites regarding environment configurations and the SRG app upgrade in the use case documentation.
